// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire@latest
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	"github.com/ddo/server-go/internal/application/usecase/health"
	"github.com/ddo/server-go/internal/bootstrap"
	"github.com/ddo/server-go/internal/infrastructure/config"
	"github.com/ddo/server-go/internal/infrastructure/logger"
	"github.com/ddo/server-go/internal/infrastructure/server"
	httpinterface "github.com/ddo/server-go/internal/interfaces/http"
	"github.com/ddo/server-go/internal/interfaces/http/handler"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp(cfgPath string) (*bootstrap.App, func(), error) {
	// 加载配置
	viperLoader := config.NewViperLoader()
	cfg, err := provideConfig(viperLoader, cfgPath)
	if err != nil {
		return nil, nil, err
	}

	// 创建 cleanup 函数
	cleanup := func() {}

	// 初始化日志
	zapLogger, logCleanup, err := provideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	cleanup = func() {
		logCleanup()
	}

	// 初始化路由
	router := httpinterface.NewRouter(zapLogger)
	engine := provideEngine(router)

	// 初始化用例
	version := provideVersion()
	checkHealthUseCase := health.NewUseCase(version)

	// 初始化 Handler
	healthHandler := handler.NewHealthHandler(checkHealthUseCase, version)

	// 注册路由
	router.RegisterRoutes(healthHandler)

	// 初始化服务器
	ginServer := server.NewGinServer(cfg, zapLogger, engine)

	// 创建应用
	app := bootstrap.NewApp(cfg, zapLogger, ginServer)

	return app, cleanup, nil
}

// provideConfig 提供配置
func provideConfig(loader *config.ViperLoader, cfgPath string) (*config.Config, error) {
	return loader.Load(cfgPath)
}

// provideLogger 提供日志实例
func provideLogger(cfg *config.Config) (*zap.Logger, func(), error) {
	log, err := logger.NewZapLogger(
		cfg.Log.Level,
		cfg.Log.Format,
		cfg.Log.Output,
	)
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		_ = log.Sync()
	}

	return log, cleanup, nil
}

// provideEngine 提供 Gin Engine
func provideEngine(router *httpinterface.Router) *gin.Engine {
	return router.Engine()
}

// provideVersion 提供版本号
func provideVersion() string {
	return appVersion
}
