// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire@latest
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ddo/server-go/internal/application/usecase/health"
	"github.com/ddo/server-go/internal/bootstrap"
	"github.com/ddo/server-go/internal/db"
	"github.com/ddo/server-go/internal/infrastructure/config"
	"github.com/ddo/server-go/internal/infrastructure/logger"
	"github.com/ddo/server-go/internal/infrastructure/server"
	"github.com/ddo/server-go/internal/queue"
	http "github.com/ddo/server-go/internal/interfaces/http"
	"github.com/ddo/server-go/internal/interfaces/http/handler"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp(cfgPath string) (*bootstrap.App, func(), error) {
	// 加载配置
	viperLoader := config.NewViperLoader()
	cfg, err := provideConfig(viperLoader, cfgPath)
	if err != nil {
		return nil, nil, err
	}

	// 初始化日志
	zapLogger, logCleanup, err := provideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}

	// 初始化 MySQL 连接
	mySQLConn, mysqlCleanup, err := provideMySQLConn(cfg, zapLogger)
	if err != nil {
		logCleanup()
		return nil, nil, err
	}

	// 初始化消息队列
	queueQueue, queueCleanup, err := provideQueue(cfg, zapLogger)
	if err != nil {
		mysqlCleanup()
		logCleanup()
		return nil, nil, err
	}

	// 初始化路由
	router := http.NewRouter(zapLogger)
	engine := provideEngine(router)

	// 初始化用例
	version := provideVersion()
	checkHealthUseCase := health.NewUseCase(version, mySQLConn)

	// 初始化 Handler
	healthHandler := handler.NewHealthHandler(checkHealthUseCase, version)

	// 注册路由
	router.RegisterRoutes(healthHandler)

	// 初始化服务器
	ginServer := server.NewGinServer(cfg, zapLogger, engine)

	// 创建应用
	app := bootstrap.NewApp(cfg, zapLogger, ginServer, mySQLConn, queueQueue)

	// 组装 cleanup 函数
	cleanup := func() {
		queueCleanup()
		mysqlCleanup()
		logCleanup()
	}

	return app, cleanup, nil
}

// provideConfig 提供配置
func provideConfig(loader *config.ViperLoader, cfgPath string) (*config.Config, error) {
	return loader.Load(cfgPath)
}

// provideLogger 提供日志实例
func provideLogger(cfg *config.Config) (*zap.Logger, func(), error) {
	log, err := logger.NewZapLogger(
		cfg.Log.Level,
		cfg.Log.Format,
		cfg.Log.Output,
	)
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		_ = log.Sync()
	}

	return log, cleanup, nil
}

// provideMySQLConn 提供 MySQL 连接
func provideMySQLConn(cfg *config.Config, logger *zap.Logger) (*db.MySQLConn, func(), error) {
	conn, cleanup, err := db.NewMySQLConn(cfg)
	if err != nil {
		logger.Error("Failed to connect to MySQL", zap.Error(err))
		// MySQL 连接失败不应阻止服务启动
		// 返回 nil，服务启动后可以通过健康检查发现
		return nil, func() {}, nil
	}
	return conn, cleanup, nil
}

// provideQueue 提供消息队列
func provideQueue(cfg *config.Config, logger *zap.Logger) (queue.Queue, func(), error) {
	// 使用默认配置，数据目录在 ~/.ddo/data/badger/queue
	qCfg := queue.DefaultConfig(cfg.Database.DBName)
	q, cleanup, err := queue.NewBadgerQueue(qCfg, logger)
	if err != nil {
		logger.Error("Failed to create queue", zap.Error(err))
		return nil, func() {}, err
	}
	return q, cleanup, nil
}

// provideEngine 提供 Gin Engine
func provideEngine(router *http.Router) *gin.Engine {
	return router.Engine()
}

// provideVersion 提供版本号
func provideVersion() string {
	return appVersion
}
